site_name: taxin-pages
theme:
  name: material
  language: ja
  features:
    - tabs
plugins:
  - search:
      lang: 
        - en
        - ja
nav:
  - self-introduction: introduction.md
  - other: others.md

