site_name: taxin-pages
docs_dir: 'docs'
theme:
  name: 'material'
  language: 'ja'
  features:
    - tabs
markdown_extensions:
  - codehilite
  - footnotes
  - meta
  - admonition
  - plantuml_markdown:
      server: http://www.planturl.com/planturl
plugins:
  - search:
  - git-revision-date-localized
nav:
  - はじめに:
    - introduction: introduction.md
    - links: others.md

