site_name: taxin-pages
repo_url: https://github.com/TaxiN/study-wiki
theme:
  name: material
  language: 'ja'
  features:
    tabs: true
extra:
  search:
    language: 'ja'
markdown_extensions:
  - codehilite
nav:
  - introduction: introduction.md
