name: Deploy mkdocs

on:
  pull_request:
    # masterへのPRをトリガーとして実行する
    branches:
      - master
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout branch 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: configure git info
        run: |
          git config --global user.name "github-actions-for-deploy"
          git config --global user.email deploy-actions@github.com

      - name: check git status/branch
        run: |
          git status
          git branch

      # mkdocsを利用するためのpython環境のsetup
      - name: setup python env
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: mkdocs build and deploy
        run: |
           remote_repo="https://x-access-token:${PERSONAL_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
           git remote rm origin
           git remote add origin "${remote_repo}"
           # git fetch --depth=1 origin master
           ls -l "${GITHUB_WORKSPACE}"
           mkdocs gh-deploy --config-file "${GITHUB_WORKSPACE}/mkdocs.yml" 

      - name: notify slack
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow  
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

