name: Deploy mkdocs

on:
  push:
    # work branchの修正をトリガーとして実行する
    branches:
      - work
    paths:
      - 'docs/*.md'
      - 'docs/*/*.md'
      - 'docs/imgs/*'
      - 'mkdocs.yml'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout branch 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # mkdocsを利用するためのpython環境のsetup
      - name: setup python env
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: mkdocs build
        run: mkdocs build     

      - name: mkdocs deploy
        run: |
           git fetch --depth=1 origin master
           mkdocs gh-deploy

      - name: notify slack
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow  
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

